<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "comprobante".
 *
 * @property integer $id
 * @property string $nro_remito
 * @property string $fecha_inicial
 * @property string $fecha_emision
 * @property double $total
 * @property integer $proveedorid
 * @property string $descripcion
 *
 * @property \app\models\Proveedor $proveedor
 * @property \app\models\Inventario[] $inventarios
 * @property string $aliasModel
 */
abstract class Comprobante extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'comprobante';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['nro_remito', 'fecha_inicial', 'fecha_emision'], 'required'],
            [['fecha_inicial', 'fecha_emision'], 'safe'],
            [['total'], 'number'],
            [['proveedorid'], 'integer'],
            [['descripcion'], 'string'],
            [['nro_remito'], 'string', 'max' => 45],
            [['nro_remito'], 'unique'],
            [['proveedorid'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Proveedor::className(), 'targetAttribute' => ['proveedorid' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'nro_remito' => 'Nro Remito',
            'fecha_inicial' => 'Fecha Inicial',
            'fecha_emision' => 'Fecha Emision',
            'total' => 'Total',
            'proveedorid' => 'Proveedorid',
            'descripcion' => 'Descripcion',
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeHints()
    {
        return array_merge(parent::attributeHints(), [
            'fecha_inicial' => 'Fecha de registro en el servidor
',
            'fecha_emision' => 'fecha que se emite el comprobate
',
        ]);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getProveedor()
    {
        return $this->hasOne(\app\models\Proveedor::className(), ['id' => 'proveedorid']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getInventarios()
    {
        return $this->hasMany(\app\models\Inventario::className(), ['comprobanteid' => 'id']);
    }




}
