<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "egreso_descripcion".
 *
 * @property integer $id
 * @property integer $egresoid
 * @property integer $productoid
 * @property integer $cantidad
 * @property string $descripcion
 *
 * @property \app\models\Egreso $egreso
 * @property \app\models\Producto $producto
 * @property string $aliasModel
 */
abstract class EgresoDescripcion extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'egreso_descripcion';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['egresoid', 'productoid', 'cantidad'], 'integer'],
            [['descripcion'], 'string'],
            [['egresoid'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Egreso::className(), 'targetAttribute' => ['egresoid' => 'id']],
            [['productoid'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Producto::className(), 'targetAttribute' => ['productoid' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'egresoid' => 'Egresoid',
            'productoid' => 'Productoid',
            'cantidad' => 'Cantidad',
            'descripcion' => 'Descripcion',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getEgreso()
    {
        return $this->hasOne(\app\models\Egreso::className(), ['id' => 'egresoid']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getProducto()
    {
        return $this->hasOne(\app\models\Producto::className(), ['id' => 'productoid']);
    }




}
