<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "egreso".
 *
 * @property string $fecha
 * @property string $origen
 * @property string $destino_nombre
 * @property integer $destino_localidadid
 * @property string $descripcion
 * @property string $nro_acta
 * @property integer $tipo_egresoid
 * @property string $fecha_inicial
 * @property integer $id
 * @property string $suscrito
 *
 * @property \app\models\EgresoDescripcion[] $egresoDescripcions
 * @property \app\models\Inventario[] $inventarios
 * @property \app\models\TipoEgreso $tipoEgreso
 * @property string $aliasModel
 */
abstract class Egreso extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'egreso';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['fecha', 'destino_nombre', 'destino_localidadid', 'fecha_inicial'], 'required'],
            [['fecha', 'fecha_inicial'], 'safe'],
            [['destino_localidadid', 'tipo_egresoid'], 'integer'],
            [['descripcion'], 'string'],
            [['origen', 'destino_nombre'], 'string', 'max' => 100],
            [['nro_acta'], 'string', 'max' => 20],
            [['suscrito'], 'string', 'max' => 70],
            [['tipo_egresoid'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\TipoEgreso::className(), 'targetAttribute' => ['tipo_egresoid' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'fecha' => 'Fecha',
            'origen' => 'Origen',
            'destino_nombre' => 'Destino Nombre',
            'destino_localidadid' => 'Destino Localidadid',
            'descripcion' => 'Descripcion',
            'nro_acta' => 'Nro Acta',
            'tipo_egresoid' => 'Tipo Egresoid',
            'fecha_inicial' => 'Fecha Inicial',
            'id' => 'ID',
            'suscrito' => 'Suscrito',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getEgresoDescripcions()
    {
        return $this->hasMany(\app\models\EgresoDescripcion::className(), ['egresoid' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getInventarios()
    {
        return $this->hasMany(\app\models\Inventario::className(), ['egresoid' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getTipoEgreso()
    {
        return $this->hasOne(\app\models\TipoEgreso::className(), ['id' => 'tipo_egresoid']);
    }




}
