<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "inventario".
 *
 * @property integer $comprobanteid
 * @property integer $productoid
 * @property string $fecha_vencimiento
 * @property double $precio_unitario
 * @property integer $defectuoso
 * @property integer $egresoid
 * @property integer $depositoid
 * @property integer $id
 * @property integer $falta
 *
 * @property \app\models\Comprobante $comprobante
 * @property \app\models\Producto $producto
 * @property \app\models\Deposito $deposito
 * @property \app\models\Egreso $egreso
 * @property string $aliasModel
 */
abstract class Inventario extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'inventario';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['comprobanteid', 'productoid'], 'required'],
            [['comprobanteid', 'productoid', 'defectuoso', 'egresoid', 'depositoid', 'falta'], 'integer'],
            [['fecha_vencimiento'], 'safe'],
            [['precio_unitario'], 'number'],
            [['comprobanteid'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Comprobante::className(), 'targetAttribute' => ['comprobanteid' => 'id']],
            [['productoid'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Producto::className(), 'targetAttribute' => ['productoid' => 'id']],
            [['depositoid'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Deposito::className(), 'targetAttribute' => ['depositoid' => 'id']],
            [['egresoid'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Egreso::className(), 'targetAttribute' => ['egresoid' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'comprobanteid' => 'Comprobanteid',
            'productoid' => 'Productoid',
            'fecha_vencimiento' => 'Fecha Vencimiento',
            'precio_unitario' => 'Precio Unitario',
            'defectuoso' => 'Defectuoso',
            'egresoid' => 'Egresoid',
            'depositoid' => 'Depositoid',
            'id' => 'ID',
            'falta' => 'Falta',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getComprobante()
    {
        return $this->hasOne(\app\models\Comprobante::className(), ['id' => 'comprobanteid']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getProducto()
    {
        return $this->hasOne(\app\models\Producto::className(), ['id' => 'productoid']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getDeposito()
    {
        return $this->hasOne(\app\models\Deposito::className(), ['id' => 'depositoid']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getEgreso()
    {
        return $this->hasOne(\app\models\Egreso::className(), ['id' => 'egresoid']);
    }




}
