<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "proveedor".
 *
 * @property integer $id
 * @property string $nombre
 * @property string $cuit
 * @property integer $activo
 *
 * @property \app\models\Comprobante[] $comprobantes
 * @property string $aliasModel
 */
abstract class Proveedor extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'proveedor';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['nombre'], 'required'],
            [['activo'], 'integer'],
            [['nombre'], 'string', 'max' => 100],
            [['cuit'], 'string', 'max' => 45]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'nombre' => 'Nombre',
            'cuit' => 'Cuit',
            'activo' => 'Activo',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getComprobantes()
    {
        return $this->hasMany(\app\models\Comprobante::className(), ['proveedorid' => 'id']);
    }




}
